name: Deploy PHP Site to IONOS (develop)

on:
  push:
    branches: [ develop ]

concurrency:
  group: deploy-develop
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote host to known_hosts
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H "${{ secrets.REMOTE_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Sanity check SSH
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo 'SSH OK'"

      - name: Ensure destination exists (remote)
        env:
          DEST: "${{ secrets.REMOTE_CHEMIN }}/${{ vars.ADRESSE_GLOBAL }}/${{ vars.ADRESSE_DEV }}"
        run: |
          set -euo pipefail
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "mkdir -p \"$DEST\""

      - name: Rsync to server
        env:
          DEST: "${{ secrets.REMOTE_CHEMIN }}/${{ vars.ADRESSE_GLOBAL }}/${{ vars.ADRESSE_DEV }}"
        run: |
          set -euo pipefail
          if [ ! -f .rsync-ignore ]; then
            printf ".git\nnode_modules\nvendor\n" > .rsync-ignore
          fi
          rsync -avz --compress-level=9 --delete-after --human-readable \
            --exclude-from=".rsync-ignore" \
            -e "ssh -o StrictHostKeyChecking=yes" \
            ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:"$DEST"

      # (Optionnel) Build/Composer côté serveur
      # - name: Post-deploy tasks (remote)
      #   run: |
      #     DEST="${{ secrets.REMOTE_CHEMIN }}/${{ vars.ADRESSE_GLOBAL }}/${{ vars.ADRESSE_DEV }}"
      #     ssh -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
      #       set -e
      #       cd "$DEST"
      #       # composer install --no-dev --optimize-autoloader
      #       # php bin/console cache:clear --env=prod
      #       # php bin/console doctrine:migrations:migrate --no-interaction
      #     EOF
