name: Add Ticket Number to PR Title

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Title
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = github.context.payload.pull_request;
            if (!pr) return;
            const prTitle = pr.title || '';
            const prNumber = pr.number;

            console.log(`Current PR Title: ${prTitle}`);
            console.log(`PR Number: ${prNumber}`);

            if (/\[(Ticket|PR)_\d+\]/.test(prTitle)) {
              console.log('PR title already contains a Ticket or PR tag. No update needed.');
              return;
            }

            let cleanedTitle = prTitle.replace(/Eric CORBISIER\/\/\s*/i, '').trim();

            // enlever préfixe jusqu'à '//' ou '/' (optional selon ta convention)
            cleanedTitle = cleanedTitle.replace(/.*\/\/\s*|.*\/\s*/g, '').trim();

            let ticketMatch = cleanedTitle.match(/^(\d+)\s+/);
            let ticketNumber = ticketMatch ? `Ticket_${ticketMatch[1]}` : `PR_${prNumber}`;

            if (ticketMatch) {
              cleanedTitle = cleanedTitle.replace(ticketMatch[0], '').trim();
            }

            const newTitle = `[${ticketNumber}] ${cleanedTitle}`;
            if (newTitle === prTitle) {
              console.log('Title unchanged.');
              return;
            }

            await github.rest.pulls.update({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number: prNumber,
              title: newTitle
            });

            console.log(`PR title successfully updated to: ${newTitle}`);
